-- =========================================================
-- AgentHub Test Schema - POSTGRES
-- Auto-generated by com.agenthub.test.schema.SchemaFileGenerator
-- DO NOT EDIT: regenerate via :generateSchemaDdl
-- =========================================================

CREATE SCHEMA IF NOT EXISTS app;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
SET search_path TO app, public;

-- Table: agent
CREATE TABLE IF NOT EXISTS app.agent (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  agent_code varchar(255),
  name varchar(255),
  description text,
  status varchar(255),
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by varchar(255),
  updated_by varchar(255),
  PRIMARY KEY (id)
);

-- Table: agent_config
CREATE TABLE IF NOT EXISTS app.agent_config (
  id varchar(64) NOT NULL,
  agent_id varchar(255),
  category varchar(255),
  type varchar(255),
  config_id varchar(255),
  name varchar(255),
  description text,
  priority integer,
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: agent_data_source
CREATE TABLE IF NOT EXISTS app.agent_data_source (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  protocol varchar(255),
  endpoint_uri text,
  properties_json varchar(255),
  enabled boolean,
  status varchar(255),
  last_error_message varchar(255),
  last_checked_at timestamptz,
  permission_policy_id varchar(255),
  schema_id varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  created_by varchar(255),
  updated_by varchar(255),
  PRIMARY KEY (id)
);

-- Table: agent_execution_plan
CREATE TABLE IF NOT EXISTS app.agent_execution_plan (
  id varchar(64) NOT NULL,
  agent_id varchar(255),
  session_id varchar(255),
  goal varchar(255),
  status varchar(255),
  current_step_index integer,
  result varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: agent_plan_step
CREATE TABLE IF NOT EXISTS app.agent_plan_step (
  id varchar(64) NOT NULL,
  plan_id varchar(255),
  step_order integer,
  description text,
  tool_name varchar(255),
  tool_input varchar(255),
  status varchar(255),
  step_output varchar(255),
  subagent_id varchar(255),
  subsession_id varchar(255),
  depends_on varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: agent_task
CREATE TABLE IF NOT EXISTS app.agent_task (
  id varchar(64) NOT NULL,
  stage_id varchar(255),
  workflow_id varchar(255),
  task_description text,
  subagent_id varchar(255),
  subsession_id varchar(255),
  status varchar(255),
  result varchar(255),
  model_config_id varchar(255),
  tool_names varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: agent_team
CREATE TABLE IF NOT EXISTS app.agent_team (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  team_code varchar(255),
  name varchar(255),
  description text,
  coordination_mode varchar(255),
  member_config varchar(255),
  status varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: alerts
CREATE TABLE IF NOT EXISTS app.alerts (
  id varchar(64) NOT NULL,
  alert_level varchar(255),
  alert_type varchar(255),
  title varchar(255),
  message varchar(255),
  run_id varchar(255),
  agent_id varchar(255),
  trace_id varchar(255),
  metadata varchar(255),
  resolved boolean,
  resolved_at timestamptz,
  resolved_by varchar(255),
  tenant_id varchar(255),
  workspace_id varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: app_user
CREATE TABLE IF NOT EXISTS app.app_user (
  id varchar(64) NOT NULL,
  username varchar(255),
  password_hash varchar(255),
  tenant_id varchar(255),
  status varchar(255),
  email varchar(255),
  display_name varchar(255),
  auth_source varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: audit_log
CREATE TABLE IF NOT EXISTS app.audit_log (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  actor_id varchar(255),
  actor_type varchar(255),
  agent_id varchar(255),
  session_id varchar(255),
  resource_type varchar(255),
  resource_id varchar(255),
  resource_name varchar(255),
  action varchar(255),
  status varchar(255),
  request varchar(255),
  response varchar(255),
  error_message varchar(255),
  metadata varchar(255),
  elapsed_ms bigint,
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: chat_message
CREATE TABLE IF NOT EXISTS app.chat_message (
  id varchar(64) NOT NULL,
  session_id varchar(255),
  role varchar(255),
  content text,
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: dag_workflow
CREATE TABLE IF NOT EXISTS app.dag_workflow (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  workflow_code varchar(255),
  name varchar(255),
  description text,
  graph_definition varchar(255),
  status varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: dag_workflow_execution
CREATE TABLE IF NOT EXISTS app.dag_workflow_execution (
  id varchar(64) NOT NULL,
  workflow_id varchar(255),
  tenant_id varchar(255),
  workspace_id varchar(255),
  execution_id varchar(255),
  status varchar(255),
  input varchar(255),
  output varchar(255),
  error_info varchar(255),
  start_time timestamptz,
  end_time timestamptz,
  duration bigint,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: data_source_column
CREATE TABLE IF NOT EXISTS app.data_source_column (
  id varchar(64) NOT NULL,
  table_id varchar(255),
  name varchar(255),
  type varchar(255),
  nullable boolean,
  is_primary boolean,
  default_value varchar(255),
  description text,
  is_pii boolean,
  pii_type varchar(255),
  column_order integer,
  PRIMARY KEY (id)
);

-- Table: data_source_schema
CREATE TABLE IF NOT EXISTS app.data_source_schema (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  data_source_id varchar(255),
  display_name varchar(255),
  description text,
  introspected boolean,
  last_introspected_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: data_source_table
CREATE TABLE IF NOT EXISTS app.data_source_table (
  id varchar(64) NOT NULL,
  schema_id varchar(255),
  name varchar(255),
  display_name varchar(255),
  description text,
  allowed_operations varchar(255),
  sample_data_json varchar(255),
  table_order integer,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: document_chunk
CREATE TABLE IF NOT EXISTS app.document_chunk (
  id varchar(64) NOT NULL,
  chunk_id varchar(255),
  document_id varchar(255),
  kb_id varchar(255),
  chunk_index integer,
  token_count integer,
  PRIMARY KEY (id)
);

-- Table: dynamic_workflow
CREATE TABLE IF NOT EXISTS app.dynamic_workflow (
  id varchar(64) NOT NULL,
  agent_id varchar(255),
  session_id varchar(255),
  task varchar(255),
  pattern varchar(255),
  status varchar(255),
  result varchar(255),
  max_concurrent_agents integer,
  total_tokens_used integer,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: guardrail_policy
CREATE TABLE IF NOT EXISTS app.guardrail_policy (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  input_validation_enabled boolean,
  output_validation_enabled boolean,
  pii_detection_enabled boolean,
  pii_masking_enabled boolean,
  prompt_injection_detection boolean,
  max_input_length integer,
  max_output_length integer,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: http_tools
CREATE TABLE IF NOT EXISTS app.http_tools (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  enabled boolean,
  endpoint varchar(255),
  auth_type varchar(255),
  input_schema varchar(255),
  timeout_ms integer,
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: iam_refresh_token_session
CREATE TABLE IF NOT EXISTS app.iam_refresh_token_session (
  token varchar(255) NOT NULL,
  subject varchar(255),
  expires_at timestamptz,
  PRIMARY KEY (token)
);

-- Table: ingestion_document
CREATE TABLE IF NOT EXISTS app.ingestion_document (
  id varchar(64) NOT NULL,
  kb_id varchar(255),
  job_id varchar(255),
  file_name varchar(255),
  content_type text,
  size bigint,
  storage_path varchar(255),
  status varchar(255),
  PRIMARY KEY (id)
);

-- Table: ingestion_job
CREATE TABLE IF NOT EXISTS app.ingestion_job (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  kb_id varchar(255),
  document_id varchar(255),
  trigger_type varchar(255),
  status varchar(255),
  progress integer,
  parser_name varchar(255),
  embedding_model varchar(255),
  index_version integer,
  document_count integer,
  error_code varchar(255),
  error_message varchar(255),
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: knowledge_base
CREATE TABLE IF NOT EXISTS app.knowledge_base (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  kb_code varchar(255),
  name varchar(255),
  description text,
  status varchar(255),
  created_at timestamptz,
  created_by varchar(255),
  updated_at timestamptz,
  updated_by varchar(255),
  vector_store_config_id varchar(255),
  embedding_model_config_id varchar(255),
  chat_model_config_id varchar(255),
  PRIMARY KEY (id)
);

-- Table: kv_hash
CREATE TABLE IF NOT EXISTS app.kv_hash (
  kv_key varchar(255) NOT NULL,
  field varchar(255),
  kv_value varchar(255),
  PRIMARY KEY (kv_key)
);

-- Table: kv_list
CREATE TABLE IF NOT EXISTS app.kv_list (
  kv_key varchar(255) NOT NULL,
  list_index bigint,
  kv_value varchar(255),
  PRIMARY KEY (kv_key)
);

-- Table: kv_set
CREATE TABLE IF NOT EXISTS app.kv_set (
  kv_key varchar(255) NOT NULL,
  member varchar(255),
  PRIMARY KEY (kv_key)
);

-- Table: kv_store
CREATE TABLE IF NOT EXISTS app.kv_store (
  kv_key varchar(255) NOT NULL,
  kv_value varchar(255),
  kv_type varchar(255),
  expire_time bigint,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (kv_key)
);

-- Table: kv_zset
CREATE TABLE IF NOT EXISTS app.kv_zset (
  kv_key varchar(255) NOT NULL,
  member varchar(255),
  score double precision,
  PRIMARY KEY (kv_key)
);

-- Table: mcp_tool
CREATE TABLE IF NOT EXISTS app.mcp_tool (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  server_url text,
  server_type varchar(255),
  command varchar(255),
  args varchar(255),
  env varchar(255),
  async boolean,
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: memory
CREATE TABLE IF NOT EXISTS app.memory (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  agent_id varchar(255),
  name varchar(255),
  memory_type varchar(255),
  content text,
  metadata varchar(255),
  importance double precision,
  expires_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: message_pushes
CREATE TABLE IF NOT EXISTS app.message_pushes (
  id varchar(64) NOT NULL,
  message_id varchar(255),
  run_id varchar(255),
  role varchar(255),
  content text,
  metadata varchar(255),
  timestamp timestamptz,
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: metrics
CREATE TABLE IF NOT EXISTS app.metrics (
  id varchar(64) NOT NULL,
  metric_type varchar(255),
  metric_name varchar(255),
  metric_value double precision,
  run_id varchar(255),
  agent_id varchar(255),
  trace_id varchar(255),
  span_id varchar(255),
  labels varchar(255),
  timestamp timestamptz,
  tenant_id varchar(255),
  workspace_id varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: model_config
CREATE TABLE IF NOT EXISTS app.model_config (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  type varchar(255),
  supplier varchar(255),
  api_key varchar(255),
  base_url text,
  model varchar(255),
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  created_by varchar(255),
  PRIMARY KEY (id)
);

-- Table: model_policy
CREATE TABLE IF NOT EXISTS app.model_policy (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  temperature double precision,
  max_tokens integer,
  top_p double precision,
  frequency_penalty double precision,
  presence_penalty double precision,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: node_execution_result
CREATE TABLE IF NOT EXISTS app.node_execution_result (
  id varchar(64) NOT NULL,
  execution_id varchar(255),
  node_id varchar(255),
  node_name varchar(255),
  node_type varchar(255),
  status varchar(255),
  input varchar(255),
  output varchar(255),
  error_info varchar(255),
  start_time timestamptz,
  end_time timestamptz,
  duration bigint,
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: permission_strategy
CREATE TABLE IF NOT EXISTS app.permission_strategy (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  allowed_roles varchar(255),
  allowed_operations varchar(255),
  protocol_blocklist varchar(255),
  dangerous_sql_block boolean,
  require_approval_for varchar(255),
  table_permissions varchar(255),
  rate_limit_per_minute integer,
  rate_limit_per_hour integer,
  audit_log_enabled boolean,
  audit_log_retention_days integer,
  pii_masking_on_result boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: prompt_template
CREATE TABLE IF NOT EXISTS app.prompt_template (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  category varchar(255),
  content text,
  variables varchar(255),
  active boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: retrieval_policy
CREATE TABLE IF NOT EXISTS app.retrieval_policy (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  retrieval_type varchar(255),
  top_k integer,
  score_threshold double precision,
  enable_rerank boolean,
  enable_query_rewrite boolean,
  enable_text_search boolean,
  enable_vector_search boolean,
  rerank_model varchar(255),
  vector_weight double precision,
  keyword_weight double precision,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: run_registrations
CREATE TABLE IF NOT EXISTS app.run_registrations (
  id varchar(64) NOT NULL,
  project varchar(255),
  name varchar(255),
  timestamp timestamptz,
  pid integer,
  status varchar(255),
  run_dir varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: scheduled_task
CREATE TABLE IF NOT EXISTS app.scheduled_task (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  task_code varchar(255),
  name varchar(255),
  description text,
  task_type varchar(255),
  cron_expression varchar(255),
  executor_config varchar(255),
  prompt varchar(255),
  enabled boolean,
  last_execute_time timestamptz,
  next_execute_time timestamptz,
  status varchar(255),
  agent_id varchar(255),
  last_run_result varchar(255),
  run_count integer,
  created_at timestamptz,
  updated_at timestamptz,
  created_by varchar(255),
  updated_by varchar(255),
  PRIMARY KEY (id)
);

-- Table: session
CREATE TABLE IF NOT EXISTS app.session (
  id varchar(64) NOT NULL,
  agent_id varchar(255),
  name varchar(255),
  tenant_id varchar(255),
  workspace_id varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: skill
CREATE TABLE IF NOT EXISTS app.skill (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  skill_code varchar(255),
  name varchar(255),
  description text,
  skill_type varchar(255),
  skill_path varchar(255),
  skill_files_tree varchar(255),
  source varchar(255),
  source_path varchar(255),
  zip_storage_path varchar(255),
  config_id varchar(255),
  file_count integer,
  total_size bigint,
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  last_sync_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: skill_config
CREATE TABLE IF NOT EXISTS app.skill_config (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  skill_paths varchar(255),
  sync_enabled boolean,
  sync_interval integer,
  auto_sync boolean,
  enabled boolean,
  last_sync_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: skill_file
CREATE TABLE IF NOT EXISTS app.skill_file (
  id varchar(64) NOT NULL,
  skill_id varchar(255),
  tenant_id varchar(255),
  workspace_id varchar(255),
  file_path varchar(255),
  file_name varchar(255),
  file_ext varchar(255),
  file_size bigint,
  file_type varchar(255),
  encoding varchar(255),
  storage_path varchar(255),
  checksum varchar(255),
  is_directory boolean,
  metadata varchar(255),
  version integer,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: spans
CREATE TABLE IF NOT EXISTS app.spans (
  id varchar(64) NOT NULL,
  span_id varchar(255),
  trace_id varchar(255),
  parent_span_id varchar(255),
  name varchar(255),
  kind varchar(255),
  start_time_unix_nano varchar(255),
  end_time_unix_nano varchar(255),
  latency_ns bigint,
  attributes varchar(255),
  events varchar(255),
  links varchar(255),
  status_code integer,
  status_message varchar(255),
  resource varchar(255),
  scope varchar(255),
  model varchar(255),
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  conversation_id varchar(255),
  operation_name varchar(255),
  service_name varchar(255),
  start_timestamp bigint,
  end_timestamp bigint,
  duration bigint,
  status varchar(255),
  status_description text,
  run_id varchar(255),
  agent_id varchar(255),
  tenant_id varchar(255),
  workspace_id varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: subagent
CREATE TABLE IF NOT EXISTS app.subagent (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  parent_agent_id varchar(255),
  name varchar(255),
  description text,
  system_prompt varchar(255),
  model_config_id varchar(255),
  status varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: subsession
CREATE TABLE IF NOT EXISTS app.subsession (
  id varchar(64) NOT NULL,
  parent_session_id varchar(255),
  subagent_id varchar(255),
  name varchar(255),
  status varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: system_tools
CREATE TABLE IF NOT EXISTS app.system_tools (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  tool_class_name varchar(255),
  tool_name varchar(255),
  description text,
  category varchar(255),
  method_count integer,
  enabled boolean,
  system_tool boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: tenant
CREATE TABLE IF NOT EXISTS app.tenant (
  id varchar(64) NOT NULL,
  tenant_code varchar(255),
  name varchar(255),
  plan_code varchar(255),
  isolation_level varchar(255),
  status varchar(255),
  region varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: tool_policy
CREATE TABLE IF NOT EXISTS app.tool_policy (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  description text,
  max_concurrent_calls integer,
  timeout_seconds integer,
  retry_count integer,
  fallback_enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: tool_policy_binding
CREATE TABLE IF NOT EXISTS app.tool_policy_binding (
  id varchar(64) NOT NULL,
  tool_policy_id varchar(255),
  tool_id varchar(255),
  priority integer,
  enabled boolean,
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: traces
CREATE TABLE IF NOT EXISTS app.traces (
  id varchar(64) NOT NULL,
  trace_id varchar(255),
  run_id varchar(255),
  root_span_id varchar(255),
  span_count integer,
  start_time_unix_nano varchar(255),
  end_time_unix_nano varchar(255),
  duration_ns bigint,
  status_code integer,
  error_message varchar(255),
  total_tokens bigint,
  tenant_id varchar(255),
  workspace_id varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: user_input_requests
CREATE TABLE IF NOT EXISTS app.user_input_requests (
  id varchar(64) NOT NULL,
  request_id varchar(255),
  run_id varchar(255),
  agent_id varchar(255),
  agent_name varchar(255),
  structured_input varchar(255),
  created_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: vector_store_config
CREATE TABLE IF NOT EXISTS app.vector_store_config (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_id varchar(255),
  name varchar(255),
  type varchar(255),
  host varchar(255),
  port integer,
  api_key varchar(255),
  collection_name varchar(255),
  extra_params varchar(255),
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: workflow_stage
CREATE TABLE IF NOT EXISTS app.workflow_stage (
  id varchar(64) NOT NULL,
  workflow_id varchar(255),
  stage_order integer,
  name varchar(255),
  stage_type varchar(255),
  system_prompt varchar(255),
  task_template varchar(255),
  depends_on varchar(255),
  status varchar(255),
  output varchar(255),
  completed_task_count integer,
  total_task_count integer,
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

-- Table: workspace
CREATE TABLE IF NOT EXISTS app.workspace (
  id varchar(64) NOT NULL,
  tenant_id varchar(255),
  workspace_code varchar(255),
  name varchar(255),
  region varchar(255),
  status varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  PRIMARY KEY (id)
);

