package com.agenthub.test.schema;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * 多方言测试 Schema/Init SQL 文件生成器。
 * 输出到 {outputBaseDir}/{dialect}/{schema.sql, init.sql}。
 */
public final class SchemaFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(SchemaFileGenerator.class);

    public static final List<SchemaDialect> DIALECTS = List.of(
        new PostgresDialect(),
        new H2Dialect(),
        new MysqlDialect()
    );

    private SchemaFileGenerator() {
    }

    /**
     * 为所有方言生成文件
     */
    public static void generateAll(String outputBaseDir) throws IOException {
        for (SchemaDialect dialect : DIALECTS) {
            generateOne(dialect, outputBaseDir);
        }
    }

    /**
     * 为单个方言生成文件
     */
    public static void generateOne(SchemaDialect dialect, String outputBaseDir) throws IOException {
        Path dir = Paths.get(outputBaseDir, dialect.name());
        Files.createDirectories(dir);
        String schema = generateSchemaSQL(dialect);
        String init = generateInitSQL(dialect);
        Files.writeString(dir.resolve("schema.sql"), schema);
        Files.writeString(dir.resolve("init.sql"), init);
        log.info("[{}] schema.sql {} bytes, init.sql {} bytes",
            dialect.name(), schema.length(), init.length());
    }

    /**
     * 生成 schema.sql 的字符串内容
     */
    public static String generateSchemaSQL(SchemaDialect dialect) {
        StringBuilder sb = new StringBuilder();
        appendHeader(sb, dialect);
        List<EntitySchemaScanner.TableDefinition> tables = EntitySchemaScanner.scan();
        appendTables(sb, dialect, tables);
        return sb.toString();
    }

    /**
     * 生成 init.sql 的字符串内容
     */
    public static String generateInitSQL(SchemaDialect dialect) {
        StringBuilder sb = new StringBuilder();
        appendInitHeader(sb, dialect);
        List<SeedDataProvider.SeedRow> rows = new ArrayList<>(SeedDataProvider.all());
        rows.sort(Comparator.comparing(SeedDataProvider.SeedRow::table));
        for (SeedDataProvider.SeedRow row : rows) {
            appendSeedRow(sb, dialect, row);
        }
        return sb.toString();
    }

    private static void appendHeader(StringBuilder sb, SchemaDialect dialect) {
        sb.append("-- =========================================================\n");
        sb.append("-- AgentHub Test Schema - ").append(dialect.name().toUpperCase()).append("\n");
        sb.append("-- Auto-generated by com.agenthub.test.schema.SchemaFileGenerator\n");
        sb.append("-- DO NOT EDIT: regenerate via :generateSchemaDdl\n");
        sb.append("-- =========================================================\n\n");
        String header = dialect.schemaHeader();
        if (header != null && !header.isBlank()) {
            sb.append(header).append("\n");
        }
    }

    private static void appendInitHeader(StringBuilder sb, SchemaDialect dialect) {
        sb.append("-- =========================================================\n");
        sb.append("-- AgentHub Test Seed Data - ").append(dialect.name().toUpperCase()).append("\n");
        sb.append("-- Auto-generated by com.agenthub.test.schema.SchemaFileGenerator\n");
        sb.append("-- DO NOT EDIT: regenerate via :generateSchemaDdl\n");
        sb.append("-- =========================================================\n\n");
    }

    private static void appendTables(StringBuilder sb, SchemaDialect dialect,
                                     List<EntitySchemaScanner.TableDefinition> tables) {
        String prefix = dialect.schemaPrefix();
        for (EntitySchemaScanner.TableDefinition table : tables) {
            sb.append("-- Table: ").append(table.tableName).append("\n");
            sb.append("CREATE TABLE IF NOT EXISTS ").append(prefix).append(table.tableName).append(" (\n");
            List<String> colDefs = new ArrayList<>();
            String primaryKey = null;
            for (EntitySchemaScanner.ColumnDefinition col : table.columns) {
                colDefs.add(renderColumn(dialect, col));
                if (col.isPrimaryKey) {
                    primaryKey = col.columnName;
                }
            }
            if (primaryKey != null) {
                colDefs.add("  PRIMARY KEY (" + primaryKey + ")");
            }
            sb.append(String.join(",\n", colDefs));
            sb.append("\n);\n\n");
        }
    }

    private static String renderColumn(SchemaDialect dialect, EntitySchemaScanner.ColumnDefinition col) {
        StringBuilder sb = new StringBuilder();
        sb.append("  ").append(col.columnName).append(" ");
        if (col.isAutoIncrement) {
            sb.append(dialect.autoIncrementType());
        } else {
            sb.append(dialect.mapType(col.javaType, col.columnName));
        }
        if (!col.nullable) {
            sb.append(" NOT NULL");
        }
        return sb.toString();
    }

    private static void appendSeedRow(StringBuilder sb, SchemaDialect dialect, SeedDataProvider.SeedRow row) {
        String prefix = dialect.schemaPrefix();
        SchemaDialect.SqlInsert insert = new SchemaDialect.SqlInsert(
            prefix + row.table(), row.columns(), row.values(),
            row.columns().stream().filter(c -> !"id".equals(c) && !"created_at".equals(c)).toList());
        if (row.mode() == SeedDataProvider.ConflictMode.DO_NOTHING) {
            sb.append(dialect.insertOrIgnore(insert));
        } else {
            sb.append(dialect.insertOrUpdate(insert));
        }
        sb.append("\n");
    }
}
