-- =========================================================
-- AgentHub Test Schema - MYSQL
-- Auto-generated by com.agenthub.test.schema.SchemaFileGenerator
-- DO NOT EDIT: regenerate via :generateSchemaDdl
-- =========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table: agent
CREATE TABLE IF NOT EXISTS agent (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  agent_code VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  status VARCHAR(255),
  enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  PRIMARY KEY (id)
);

-- Table: agent_config
CREATE TABLE IF NOT EXISTS agent_config (
  id varchar(64) NOT NULL,
  agent_id VARCHAR(255),
  category VARCHAR(255),
  type VARCHAR(255),
  config_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  priority INT,
  enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: agent_data_source
CREATE TABLE IF NOT EXISTS agent_data_source (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  protocol VARCHAR(255),
  endpoint_uri LONGTEXT,
  properties_json VARCHAR(255),
  enabled TINYINT(1),
  status VARCHAR(255),
  last_error_message VARCHAR(255),
  last_checked_at DATETIME(6),
  permission_policy_id VARCHAR(255),
  schema_id VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  PRIMARY KEY (id)
);

-- Table: agent_execution_plan
CREATE TABLE IF NOT EXISTS agent_execution_plan (
  id varchar(64) NOT NULL,
  agent_id VARCHAR(255),
  session_id VARCHAR(255),
  goal VARCHAR(255),
  status VARCHAR(255),
  current_step_index INT,
  result VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: agent_plan_step
CREATE TABLE IF NOT EXISTS agent_plan_step (
  id varchar(64) NOT NULL,
  plan_id VARCHAR(255),
  step_order INT,
  description TEXT,
  tool_name VARCHAR(255),
  tool_input VARCHAR(255),
  status VARCHAR(255),
  step_output VARCHAR(255),
  subagent_id VARCHAR(255),
  subsession_id VARCHAR(255),
  depends_on VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: agent_task
CREATE TABLE IF NOT EXISTS agent_task (
  id varchar(64) NOT NULL,
  stage_id VARCHAR(255),
  workflow_id VARCHAR(255),
  task_description TEXT,
  subagent_id VARCHAR(255),
  subsession_id VARCHAR(255),
  status VARCHAR(255),
  result VARCHAR(255),
  model_config_id VARCHAR(255),
  tool_names VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: agent_team
CREATE TABLE IF NOT EXISTS agent_team (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  team_code VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  coordination_mode VARCHAR(255),
  member_config VARCHAR(255),
  status VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: alerts
CREATE TABLE IF NOT EXISTS alerts (
  id varchar(64) NOT NULL,
  alert_level VARCHAR(255),
  alert_type VARCHAR(255),
  title VARCHAR(255),
  message VARCHAR(255),
  run_id VARCHAR(255),
  agent_id VARCHAR(255),
  trace_id VARCHAR(255),
  metadata VARCHAR(255),
  resolved TINYINT(1),
  resolved_at DATETIME(6),
  resolved_by VARCHAR(255),
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: app_user
CREATE TABLE IF NOT EXISTS app_user (
  id varchar(64) NOT NULL,
  username VARCHAR(255),
  password_hash VARCHAR(255),
  tenant_id VARCHAR(255),
  status VARCHAR(255),
  email VARCHAR(255),
  display_name VARCHAR(255),
  auth_source VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: audit_log
CREATE TABLE IF NOT EXISTS audit_log (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  actor_id VARCHAR(255),
  actor_type VARCHAR(255),
  agent_id VARCHAR(255),
  session_id VARCHAR(255),
  resource_type VARCHAR(255),
  resource_id VARCHAR(255),
  resource_name VARCHAR(255),
  action VARCHAR(255),
  status VARCHAR(255),
  request VARCHAR(255),
  response VARCHAR(255),
  error_message VARCHAR(255),
  metadata VARCHAR(255),
  elapsed_ms BIGINT,
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: chat_message
CREATE TABLE IF NOT EXISTS chat_message (
  id varchar(64) NOT NULL,
  session_id VARCHAR(255),
  role VARCHAR(255),
  content TEXT,
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: dag_workflow
CREATE TABLE IF NOT EXISTS dag_workflow (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  workflow_code VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  graph_definition VARCHAR(255),
  status VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: dag_workflow_execution
CREATE TABLE IF NOT EXISTS dag_workflow_execution (
  id varchar(64) NOT NULL,
  workflow_id VARCHAR(255),
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  execution_id VARCHAR(255),
  status VARCHAR(255),
  input VARCHAR(255),
  output VARCHAR(255),
  error_info VARCHAR(255),
  start_time DATETIME(6),
  end_time DATETIME(6),
  duration BIGINT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: data_source_column
CREATE TABLE IF NOT EXISTS data_source_column (
  id varchar(64) NOT NULL,
  table_id VARCHAR(255),
  name VARCHAR(255),
  type VARCHAR(255),
  nullable TINYINT(1),
  is_primary TINYINT(1),
  default_value VARCHAR(255),
  description TEXT,
  is_pii TINYINT(1),
  pii_type VARCHAR(255),
  column_order INT,
  PRIMARY KEY (id)
);

-- Table: data_source_schema
CREATE TABLE IF NOT EXISTS data_source_schema (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  data_source_id VARCHAR(255),
  display_name VARCHAR(255),
  description TEXT,
  introspected TINYINT(1),
  last_introspected_at DATETIME(6),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: data_source_table
CREATE TABLE IF NOT EXISTS data_source_table (
  id varchar(64) NOT NULL,
  schema_id VARCHAR(255),
  name VARCHAR(255),
  display_name VARCHAR(255),
  description TEXT,
  allowed_operations VARCHAR(255),
  sample_data_json VARCHAR(255),
  table_order INT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: document_chunk
CREATE TABLE IF NOT EXISTS document_chunk (
  id varchar(64) NOT NULL,
  chunk_id VARCHAR(255),
  document_id VARCHAR(255),
  kb_id VARCHAR(255),
  chunk_index INT,
  token_count INT,
  PRIMARY KEY (id)
);

-- Table: dynamic_workflow
CREATE TABLE IF NOT EXISTS dynamic_workflow (
  id varchar(64) NOT NULL,
  agent_id VARCHAR(255),
  session_id VARCHAR(255),
  task VARCHAR(255),
  pattern VARCHAR(255),
  status VARCHAR(255),
  result VARCHAR(255),
  max_concurrent_agents INT,
  total_tokens_used INT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: guardrail_policy
CREATE TABLE IF NOT EXISTS guardrail_policy (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  input_validation_enabled TINYINT(1),
  output_validation_enabled TINYINT(1),
  pii_detection_enabled TINYINT(1),
  pii_masking_enabled TINYINT(1),
  prompt_injection_detection TINYINT(1),
  max_input_length INT,
  max_output_length INT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: http_tools
CREATE TABLE IF NOT EXISTS http_tools (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  enabled TINYINT(1),
  endpoint VARCHAR(255),
  auth_type VARCHAR(255),
  input_schema VARCHAR(255),
  timeout_ms INT,
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: iam_refresh_token_session
CREATE TABLE IF NOT EXISTS iam_refresh_token_session (
  token VARCHAR(255) NOT NULL,
  subject VARCHAR(255),
  expires_at DATETIME(6),
  PRIMARY KEY (token)
);

-- Table: ingestion_document
CREATE TABLE IF NOT EXISTS ingestion_document (
  id varchar(64) NOT NULL,
  kb_id VARCHAR(255),
  job_id VARCHAR(255),
  file_name VARCHAR(255),
  content_type TEXT,
  size BIGINT,
  storage_path VARCHAR(255),
  status VARCHAR(255),
  PRIMARY KEY (id)
);

-- Table: ingestion_job
CREATE TABLE IF NOT EXISTS ingestion_job (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  kb_id VARCHAR(255),
  document_id VARCHAR(255),
  trigger_type VARCHAR(255),
  status VARCHAR(255),
  progress INT,
  parser_name VARCHAR(255),
  embedding_model VARCHAR(255),
  index_version INT,
  document_count INT,
  error_code VARCHAR(255),
  error_message VARCHAR(255),
  started_at DATETIME(6),
  ended_at DATETIME(6),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: knowledge_base
CREATE TABLE IF NOT EXISTS knowledge_base (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  kb_code VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  status VARCHAR(255),
  created_at DATETIME(6),
  created_by VARCHAR(255),
  updated_at DATETIME(6),
  updated_by VARCHAR(255),
  vector_store_config_id VARCHAR(255),
  embedding_model_config_id VARCHAR(255),
  chat_model_config_id VARCHAR(255),
  PRIMARY KEY (id)
);

-- Table: kv_hash
CREATE TABLE IF NOT EXISTS kv_hash (
  kv_key VARCHAR(255) NOT NULL,
  field VARCHAR(255),
  kv_value VARCHAR(255),
  PRIMARY KEY (kv_key)
);

-- Table: kv_list
CREATE TABLE IF NOT EXISTS kv_list (
  kv_key VARCHAR(255) NOT NULL,
  list_index BIGINT,
  kv_value VARCHAR(255),
  PRIMARY KEY (kv_key)
);

-- Table: kv_set
CREATE TABLE IF NOT EXISTS kv_set (
  kv_key VARCHAR(255) NOT NULL,
  member VARCHAR(255),
  PRIMARY KEY (kv_key)
);

-- Table: kv_store
CREATE TABLE IF NOT EXISTS kv_store (
  kv_key VARCHAR(255) NOT NULL,
  kv_value VARCHAR(255),
  kv_type VARCHAR(255),
  expire_time BIGINT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (kv_key)
);

-- Table: kv_zset
CREATE TABLE IF NOT EXISTS kv_zset (
  kv_key VARCHAR(255) NOT NULL,
  member VARCHAR(255),
  score DOUBLE,
  PRIMARY KEY (kv_key)
);

-- Table: mcp_tool
CREATE TABLE IF NOT EXISTS mcp_tool (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  server_url LONGTEXT,
  server_type VARCHAR(255),
  command VARCHAR(255),
  args VARCHAR(255),
  env VARCHAR(255),
  async TINYINT(1),
  enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: memory
CREATE TABLE IF NOT EXISTS memory (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  agent_id VARCHAR(255),
  name VARCHAR(255),
  memory_type VARCHAR(255),
  content TEXT,
  metadata VARCHAR(255),
  importance DOUBLE,
  expires_at DATETIME(6),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: message_pushes
CREATE TABLE IF NOT EXISTS message_pushes (
  id varchar(64) NOT NULL,
  message_id VARCHAR(255),
  run_id VARCHAR(255),
  role VARCHAR(255),
  content TEXT,
  metadata VARCHAR(255),
  timestamp DATETIME(6),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: metrics
CREATE TABLE IF NOT EXISTS metrics (
  id varchar(64) NOT NULL,
  metric_type VARCHAR(255),
  metric_name VARCHAR(255),
  metric_value DOUBLE,
  run_id VARCHAR(255),
  agent_id VARCHAR(255),
  trace_id VARCHAR(255),
  span_id VARCHAR(255),
  labels VARCHAR(255),
  timestamp DATETIME(6),
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: model_config
CREATE TABLE IF NOT EXISTS model_config (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  type VARCHAR(255),
  supplier VARCHAR(255),
  api_key VARCHAR(255),
  base_url LONGTEXT,
  model VARCHAR(255),
  enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  created_by VARCHAR(255),
  PRIMARY KEY (id)
);

-- Table: model_policy
CREATE TABLE IF NOT EXISTS model_policy (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  temperature DOUBLE,
  max_tokens INT,
  top_p DOUBLE,
  frequency_penalty DOUBLE,
  presence_penalty DOUBLE,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: node_execution_result
CREATE TABLE IF NOT EXISTS node_execution_result (
  id varchar(64) NOT NULL,
  execution_id VARCHAR(255),
  node_id VARCHAR(255),
  node_name VARCHAR(255),
  node_type VARCHAR(255),
  status VARCHAR(255),
  input VARCHAR(255),
  output VARCHAR(255),
  error_info VARCHAR(255),
  start_time DATETIME(6),
  end_time DATETIME(6),
  duration BIGINT,
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: permission_strategy
CREATE TABLE IF NOT EXISTS permission_strategy (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  allowed_roles VARCHAR(255),
  allowed_operations VARCHAR(255),
  protocol_blocklist VARCHAR(255),
  dangerous_sql_block TINYINT(1),
  require_approval_for VARCHAR(255),
  table_permissions VARCHAR(255),
  rate_limit_per_minute INT,
  rate_limit_per_hour INT,
  audit_log_enabled TINYINT(1),
  audit_log_retention_days INT,
  pii_masking_on_result TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: prompt_template
CREATE TABLE IF NOT EXISTS prompt_template (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  category VARCHAR(255),
  content TEXT,
  variables VARCHAR(255),
  active TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: retrieval_policy
CREATE TABLE IF NOT EXISTS retrieval_policy (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  retrieval_type VARCHAR(255),
  top_k INT,
  score_threshold DOUBLE,
  enable_rerank TINYINT(1),
  enable_query_rewrite TINYINT(1),
  enable_text_search TINYINT(1),
  enable_vector_search TINYINT(1),
  rerank_model VARCHAR(255),
  vector_weight DOUBLE,
  keyword_weight DOUBLE,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: run_registrations
CREATE TABLE IF NOT EXISTS run_registrations (
  id varchar(64) NOT NULL,
  project VARCHAR(255),
  name VARCHAR(255),
  timestamp DATETIME(6),
  pid INT,
  status VARCHAR(255),
  run_dir VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: scheduled_task
CREATE TABLE IF NOT EXISTS scheduled_task (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  task_code VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  task_type VARCHAR(255),
  cron_expression VARCHAR(255),
  executor_config VARCHAR(255),
  prompt VARCHAR(255),
  enabled TINYINT(1),
  last_execute_time DATETIME(6),
  next_execute_time DATETIME(6),
  status VARCHAR(255),
  agent_id VARCHAR(255),
  last_run_result VARCHAR(255),
  run_count INT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  PRIMARY KEY (id)
);

-- Table: session
CREATE TABLE IF NOT EXISTS session (
  id varchar(64) NOT NULL,
  agent_id VARCHAR(255),
  name VARCHAR(255),
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: skill
CREATE TABLE IF NOT EXISTS skill (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  skill_code VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  skill_type VARCHAR(255),
  skill_path VARCHAR(255),
  skill_files_tree VARCHAR(255),
  source VARCHAR(255),
  source_path VARCHAR(255),
  zip_storage_path VARCHAR(255),
  config_id VARCHAR(255),
  file_count INT,
  total_size BIGINT,
  enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  last_sync_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: skill_config
CREATE TABLE IF NOT EXISTS skill_config (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  skill_paths VARCHAR(255),
  sync_enabled TINYINT(1),
  sync_interval INT,
  auto_sync TINYINT(1),
  enabled TINYINT(1),
  last_sync_at DATETIME(6),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: skill_file
CREATE TABLE IF NOT EXISTS skill_file (
  id varchar(64) NOT NULL,
  skill_id VARCHAR(255),
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  file_path VARCHAR(255),
  file_name VARCHAR(255),
  file_ext VARCHAR(255),
  file_size BIGINT,
  file_type VARCHAR(255),
  encoding VARCHAR(255),
  storage_path VARCHAR(255),
  checksum VARCHAR(255),
  is_directory TINYINT(1),
  metadata VARCHAR(255),
  version INT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: spans
CREATE TABLE IF NOT EXISTS spans (
  id varchar(64) NOT NULL,
  span_id VARCHAR(255),
  trace_id VARCHAR(255),
  parent_span_id VARCHAR(255),
  name VARCHAR(255),
  kind VARCHAR(255),
  start_time_unix_nano VARCHAR(255),
  end_time_unix_nano VARCHAR(255),
  latency_ns BIGINT,
  attributes VARCHAR(255),
  events VARCHAR(255),
  links VARCHAR(255),
  status_code INT,
  status_message VARCHAR(255),
  resource VARCHAR(255),
  scope VARCHAR(255),
  model VARCHAR(255),
  input_tokens BIGINT,
  output_tokens BIGINT,
  total_tokens BIGINT,
  conversation_id VARCHAR(255),
  operation_name VARCHAR(255),
  service_name VARCHAR(255),
  start_timestamp BIGINT,
  end_timestamp BIGINT,
  duration BIGINT,
  status VARCHAR(255),
  status_description TEXT,
  run_id VARCHAR(255),
  agent_id VARCHAR(255),
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: subagent
CREATE TABLE IF NOT EXISTS subagent (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  parent_agent_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  system_prompt VARCHAR(255),
  model_config_id VARCHAR(255),
  status VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: subsession
CREATE TABLE IF NOT EXISTS subsession (
  id varchar(64) NOT NULL,
  parent_session_id VARCHAR(255),
  subagent_id VARCHAR(255),
  name VARCHAR(255),
  status VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: system_tools
CREATE TABLE IF NOT EXISTS system_tools (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  tool_class_name VARCHAR(255),
  tool_name VARCHAR(255),
  description TEXT,
  category VARCHAR(255),
  method_count INT,
  enabled TINYINT(1),
  system_tool TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: tenant
CREATE TABLE IF NOT EXISTS tenant (
  id varchar(64) NOT NULL,
  tenant_code VARCHAR(255),
  name VARCHAR(255),
  plan_code VARCHAR(255),
  isolation_level VARCHAR(255),
  status VARCHAR(255),
  region VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: tool_policy
CREATE TABLE IF NOT EXISTS tool_policy (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  description TEXT,
  max_concurrent_calls INT,
  timeout_seconds INT,
  retry_count INT,
  fallback_enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: tool_policy_binding
CREATE TABLE IF NOT EXISTS tool_policy_binding (
  id varchar(64) NOT NULL,
  tool_policy_id VARCHAR(255),
  tool_id VARCHAR(255),
  priority INT,
  enabled TINYINT(1),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: traces
CREATE TABLE IF NOT EXISTS traces (
  id varchar(64) NOT NULL,
  trace_id VARCHAR(255),
  run_id VARCHAR(255),
  root_span_id VARCHAR(255),
  span_count INT,
  start_time_unix_nano VARCHAR(255),
  end_time_unix_nano VARCHAR(255),
  duration_ns BIGINT,
  status_code INT,
  error_message VARCHAR(255),
  total_tokens BIGINT,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: user_input_requests
CREATE TABLE IF NOT EXISTS user_input_requests (
  id varchar(64) NOT NULL,
  request_id VARCHAR(255),
  run_id VARCHAR(255),
  agent_id VARCHAR(255),
  agent_name VARCHAR(255),
  structured_input VARCHAR(255),
  created_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: vector_store_config
CREATE TABLE IF NOT EXISTS vector_store_config (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_id VARCHAR(255),
  name VARCHAR(255),
  type VARCHAR(255),
  host VARCHAR(255),
  port INT,
  api_key VARCHAR(255),
  collection_name VARCHAR(255),
  extra_params VARCHAR(255),
  enabled TINYINT(1),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: workflow_stage
CREATE TABLE IF NOT EXISTS workflow_stage (
  id varchar(64) NOT NULL,
  workflow_id VARCHAR(255),
  stage_order INT,
  name VARCHAR(255),
  stage_type VARCHAR(255),
  system_prompt VARCHAR(255),
  task_template VARCHAR(255),
  depends_on VARCHAR(255),
  status VARCHAR(255),
  output VARCHAR(255),
  completed_task_count INT,
  total_task_count INT,
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

-- Table: workspace
CREATE TABLE IF NOT EXISTS workspace (
  id varchar(64) NOT NULL,
  tenant_id VARCHAR(255),
  workspace_code VARCHAR(255),
  name VARCHAR(255),
  region VARCHAR(255),
  status VARCHAR(255),
  created_at DATETIME(6),
  updated_at DATETIME(6),
  PRIMARY KEY (id)
);

